--select dtRef,
        --descLifeCycle,
        --count(*) as qtdCliente
--
--from life_cycle
--where descLifeCycle <> 'zumbi'
--and dtRef = (select DISTINCT max(dtRef) from life_cycle)
--
--group by dtRef, descLifeCycle
--order by dtRef, descLifeCycle
--
--
drop table life_cycle